[F] weather icons
lsst-epo/rubin-obs-client pull request #307
Opened 2023-05-15 18:25 UTC by alexgoff

Add weather icons in preparation for the summit status dashboard. A new icon composer has been added that extends the `epo-react-lib` component with these icons, use `UniqueIconComposer` to access the complete set of icons. Test in Storybook by observing the `UniqueIconComposer` story and checking the display of the new icons (weather, sun, moon)

2023-05-15 18:29 UTC, alexgoff commented on components/svg/UniqueIconComposer.jsx
> +const UniqueIconComposer = (props) => (
simple reimplementation of the IconComposer that extends it with new icons and passes on other props.

2023-05-15 18:29 UTC, alexgoff commented on components/global/Header/index.js
> +import LogoFullSize from "@/components/svg/unique/site/LogoFullSize";
a little reorganization to separate out the types of unique icons

2023-05-15 22:03 UTC, blnkt requested changes
Builds fare ailing because eslint wants all .jsx files to have PropTypes defined.  You have 
```
className,
size = 24,
fill = "currentColor"
```
for all of these new weather icons.  It's not clear to me if you actually do even want the `fill` and `size` to come in as props in this case, but assuming one does, I suggest reimplementing a lil helper "shape" that probably got refactored out when the icons all migrated into the UI lib, and also there became typescript.  The shape `svg.js` file looked like this:
```
import PropTypes from "prop-types";

export const svgInternalShape = {
  className: PropTypes.string,
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
  stroke: PropTypes.string,
  fill: PropTypes.string,
  svgProps: PropTypes.object,
};

const svgShape = PropTypes.shape({
  ...svgInternalShape,
});

export default svgShape;
```
And then, I can't quite remember but I think you can then import it where needed and either do something like:|
```
Thing.propTypes = {
  ...svgInternalShape,
};
```
or
```
Thing.propTypes = svgShape
```
something like that...?

2023-05-17 19:35 UTC, blnkt approved these changes

2023-05-17 19:35 UTC, merged