[F] hourly windspeed widget
lsst-epo/rubin-obs-client pull request #330
Opened 2023-06-12 22:59 UTC by alexgoff

For JIRA: "EPO-8112 #IN-REVIEW #comment hourly windspeed widget"

New hourly windspeed widget, viewable from the summit status content block so will have to be tested locally, includes some heavy localization work

![image](https://github.com/lsst-epo/rubin-obs-client/assets/11721838/2613be65-56e7-4acd-82e6-ad554ee4334d)

2023-06-12 23:00 UTC, alexgoff commented on components/atomic/ScrollableHorizontalWrapper/styles.js
> +export const ScrollableHorizontalWrapper = styled.div`
been using this a couple times so it's time to pull it out

2023-06-12 23:02 UTC, alexgoff commented on components/widgets/TemperatureHIstoric/index.js
> +          <tbody>
this was throwing an error since it wasn't wrapped in a `tbody`

2023-06-12 23:03 UTC, alexgoff commented on components/widgets/WindspeedHourly/index.js
> +  const speedFormatters = {
set up a custom formatter for each windspeed unit, sadly knots is not included in the list of available `units` so it has to be formatted manually using the decimal formatter

2023-06-12 23:04 UTC, alexgoff commented on components/widgets/WindspeedHourly/index.js
> +                <Styled.Direction style={{ "--angle": `${direction}deg` }}>
do a simple rotation on this element to match the wind direction

2023-06-12 23:04 UTC, alexgoff commented on components/widgets/WindspeedHourly/index.js
> +                  {windspeed ? speedFormatters[unit](windspeed) : "\u00A0"}
add a non breaking space if there is no value so that the line is preserved

2023-06-13 16:57 UTC, blnkt requested changes
Error in the build:
```
Module not found: Can't resolve '@/components/widgets/TemperatureHistoric' in '/app/components/content-blocks/SummitStatus'
```

2023-06-13 21:22 UTC, blnkt approved these changes

2023-06-13 21:23 UTC, merged