[F] add daylight widget
lsst-epo/rubin-obs-client pull request #341
Opened 2023-06-27 18:01 UTC by alexgoff

Daylight widget to show the night time, twilight, and daylight hours at the Rubin Observatory. Includes accessible interpretations of daylight data.

2023-06-27 18:06 UTC, alexgoff commented on components/dynamic/SummitData/Astroweather/Current/index.js
> +const CurrentAstroweather = () => {
section for current astro weather which right now is just daylight hours

2023-06-27 18:06 UTC, alexgoff commented on components/widgets/CurrentData/patterns/Daylight/index.js
> +          <Styled.Now
the "now" indicator will read out the current time and if it is dark enough to observe

2023-06-27 18:06 UTC, alexgoff commented on helpers/index.js
> +  return string.charAt(0).toLocaleUpperCase(locale) + string.slice(1);
use optional locale setting with locale uppercase

2023-06-27 18:06 UTC, alexgoff commented on lib/observatory.js
> +export const altitude = 2663;
altitude lets us get the correct sunrise/set times

2023-06-28 17:15 UTC, blnkt requested changes
Amazing work.  The accessibility thoughtfulness is 👍 .   A couple small stylistic things:

1. Not technically a part of this PR, but I didn't notice this before: the crescent paths on the moon icon are missing a black fill.  I think it's always black for every phase (?) so you can probs inline the fill on the path element itself, rather than add `fill: #000` to all of the phase pathProps objects? 
<img width="462" alt="Screen Shot 2023-06-28 at 10 09 37 AM" src="https://github.com/lsst-epo/rubin-obs-client/assets/8166060/72800f64-3231-41af-b118-179e09f43332">

2. Also in the moon phase widget, the lower phase label gets a little smooshed on smaller screens.  Match text style of the upper label?
![Screen Shot 2023-06-28 at 9 58 08 AM](https://github.com/lsst-epo/rubin-obs-client/assets/8166060/a477f8c4-3678-45da-97a8-07a40afb3193)

3. The DayLight Legend overflows out of its panel on smaller screens
![Screen Shot 2023-06-28 at 9 39 38 AM](https://github.com/lsst-epo/rubin-obs-client/assets/8166060/beb5b991-3e3a-4b11-b7fe-e6dccb9910aa)

2023-06-29 16:23 UTC, alexgoff commented on components/atomic/WidgetBackground/styles.js
> +  --widget-padding: ${fluidScale("20px", "10px")};
scale widget padding based on screen size

2023-06-29 18:11 UTC, alexgoff commented on components/charts/ChartBase/styles.js
> +  margin-inline: auto;
use some old tricks to get centering + overflow when applicable + no vertical overflow

2023-06-29 18:11 UTC, alexgoff commented on components/layout/WidgetPreview/styles.js
> +const desktopColumns = {
change the number of columns in each widget preview at different screen sizes

2023-07-05 22:36 UTC, merged